host: localhost
info:
  contact:
    email: dgoodwin@redhat.com
    name: Devan Goodwin
  description: Standalone Hive SyncSets without reliance on Kube API, CRs, and etcd.
  license:
    name: Apache2
  title: SyncSets API.
  version: 0.0.1
paths: {}
produces:
- application/json
schemes:
- http
swagger: "2.0"
basePath: /v1
consumes:
- application/json
definitions:
  cluster:
    properties:
      kubeconfig:
        description: Kubeconfig is an admin kubeconfig file for communicating with
          the cluster.
        type: string
        x-go-name: Kubeconfig
      name:
        description: Name of the cluster.
        type: string
        x-go-name: Name
      namespace:
        description: |-
          Namespace of the cluster. Models the Kubernetes concept of Namespace as OpenShift Hive
          uses that to allow multiple clusters with the same name, separated by owner.
        type: string
        x-go-name: Namespace
    required:
    - name
    - namespace
    - kubeconfig
    title: Cluster is a representation of a Cluster we will reconcile SyncSets to.
    type: object
    x-go-name: Cluster
    x-go-package: github.com/dgoodwin/syncsets/api
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
paths:
  /:
    get:
      tags:
        - clusters
      responses:
        200:
          description: list the clusters
          schema:
            type: array
            items:
              $ref: "#/definitions/cluster"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
