---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncsets-api
  namespace: syncsets
  labels:
    app: syncsets-api
spec:
  selector:
    matchLabels:
      app: syncsets-api
  replicas: 1
  template:
    metadata:
      labels:
        app: syncsets-api
    spec:
      containers:
      # By default we will use the latest CI images published from hive master:
      - image: quay.io/dgoodwin/syncsets:latest
        imagePullPolicy: Always
        name: api
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        command:
          - /opt/services/syncsets-server
          - --port
          - "7070"
        ports:
          - containerPort: 7070
        env:
        - name: POSTGRES_PARAMS
          value: "user=postgres dbname=syncsets sslmode=disable host=postgres password=helloworld"
---
apiVersion: v1
kind: Service
metadata:
  name: syncsets-api
  namespace: syncsets
  labels:
    app: syncsets-api
spec:
  selector:
    app: syncsets-api
  ports:
  - name: http
    port: 8080
    protocol: TCP
