// Code generated by go-swagger; DO NOT EDIT.

// Package restapi SyncSets API.
//
//  Standalone Hive SyncSets without reliance on Kube API, CRs, and etcd.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /v1
//  Version: 0.0.1
//  License: Apache2
//  Contact: Devan Goodwin<dgoodwin@redhat.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
