// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Standalone Hive SyncSets without reliance on Kube API, CRs, and etcd.\nSchemes:\nhttp\nhttps\nSchemes:\nhttp\nSchemes:\nhttp\nSchemes:\nhttp\nSchemes:\nhttp\nSchemes:\nhttp\nSchemes:\nhttp",
    "title": "SyncSets API.",
    "contact": {
      "name": "Devan Goodwin",
      "email": "dgoodwin@redhat.com"
    },
    "license": {
      "name": "Apache2"
    },
    "version": "0.0.1"
  },
  "host": "localhost",
  "basePath": "/v1",
  "paths": {
    "/clusters": {
      "post": {
        "description": "Some test description that should be expanded on someday.",
        "schemes": [
          "http"
        ],
        "summary": "Create a Cluster resource.",
        "operationId": "createCluster",
        "responses": {
          "200": {
            "$ref": "#/responses/OK"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          }
        }
      }
    }
  },
  "definitions": {
    "Cluster": {
      "type": "object",
      "title": "Cluster Cluster is a representation of a Cluster we will reconcile SyncSets to.",
      "required": [
        "kubeconfig",
        "name",
        "namespace"
      ],
      "properties": {
        "kubeconfig": {
          "description": "Kubeconfig is an admin kubeconfig file for communicating with the cluster.",
          "type": "string",
          "x-go-name": "Kubeconfig"
        },
        "name": {
          "description": "Name of the cluster.",
          "type": "string",
          "x-go-name": "Name"
        },
        "namespace": {
          "description": "Namespace of the cluster. Models the Kubernetes concept of Namespace as OpenShift Hive\nuses that to allow multiple clusters with the same name, separated by owner.",
          "type": "string",
          "x-go-name": "Namespace"
        }
      },
      "x-go-package": "github.com/dgoodwin/syncsets/models"
    },
    "cluster": {
      "type": "object",
      "title": "Cluster is a representation of a Cluster we will reconcile SyncSets to.",
      "required": [
        "name",
        "namespace",
        "kubeconfig"
      ],
      "properties": {
        "kubeconfig": {
          "description": "Kubeconfig is an admin kubeconfig file for communicating with the cluster.",
          "type": "string",
          "x-go-name": "Kubeconfig"
        },
        "name": {
          "description": "Name of the cluster.",
          "type": "string",
          "x-go-name": "Name"
        },
        "namespace": {
          "description": "Namespace of the cluster. Models the Kubernetes concept of Namespace as OpenShift Hive\nuses that to allow multiple clusters with the same name, separated by owner.",
          "type": "string",
          "x-go-name": "Namespace"
        }
      },
      "x-go-name": "Cluster",
      "x-go-package": "github.com/dgoodwin/syncsets/api"
    }
  },
  "responses": {
    "BadRequest": {
      "description": "BadRequest indicates that there was an error in\nthe HTTP request.",
      "headers": {
        "ResponseCode": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "OK": {
      "description": "OK indicates that the HTTP request was successful.",
      "headers": {
        "ResponseCode": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "createClusterBadRequest": {
      "description": "CreateClusterBadRequest BadRequest indicates that there was an error in\nthe HTTP request.",
      "headers": {
        "ResponseCode": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "createClusterOK": {
      "description": "CreateClusterOK OK indicates that the HTTP request was successful.",
      "headers": {
        "ResponseCode": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Standalone Hive SyncSets without reliance on Kube API, CRs, and etcd.\nSchemes:\nhttp\nhttps\nSchemes:\nhttp\nSchemes:\nhttp\nSchemes:\nhttp\nSchemes:\nhttp\nSchemes:\nhttp\nSchemes:\nhttp",
    "title": "SyncSets API.",
    "contact": {
      "name": "Devan Goodwin",
      "email": "dgoodwin@redhat.com"
    },
    "license": {
      "name": "Apache2"
    },
    "version": "0.0.1"
  },
  "host": "localhost",
  "basePath": "/v1",
  "paths": {
    "/clusters": {
      "post": {
        "description": "Some test description that should be expanded on someday.",
        "schemes": [
          "http"
        ],
        "summary": "Create a Cluster resource.",
        "operationId": "createCluster",
        "responses": {
          "200": {
            "description": "OK indicates that the HTTP request was successful.",
            "headers": {
              "ResponseCode": {
                "type": "integer",
                "format": "int64"
              }
            }
          },
          "400": {
            "description": "BadRequest indicates that there was an error in\nthe HTTP request.",
            "headers": {
              "ResponseCode": {
                "type": "integer",
                "format": "int64"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Cluster": {
      "type": "object",
      "title": "Cluster Cluster is a representation of a Cluster we will reconcile SyncSets to.",
      "required": [
        "kubeconfig",
        "name",
        "namespace"
      ],
      "properties": {
        "kubeconfig": {
          "description": "Kubeconfig is an admin kubeconfig file for communicating with the cluster.",
          "type": "string",
          "x-go-name": "Kubeconfig"
        },
        "name": {
          "description": "Name of the cluster.",
          "type": "string",
          "x-go-name": "Name"
        },
        "namespace": {
          "description": "Namespace of the cluster. Models the Kubernetes concept of Namespace as OpenShift Hive\nuses that to allow multiple clusters with the same name, separated by owner.",
          "type": "string",
          "x-go-name": "Namespace"
        }
      },
      "x-go-package": "github.com/dgoodwin/syncsets/models"
    },
    "cluster": {
      "type": "object",
      "title": "Cluster is a representation of a Cluster we will reconcile SyncSets to.",
      "required": [
        "name",
        "namespace",
        "kubeconfig"
      ],
      "properties": {
        "kubeconfig": {
          "description": "Kubeconfig is an admin kubeconfig file for communicating with the cluster.",
          "type": "string",
          "x-go-name": "Kubeconfig"
        },
        "name": {
          "description": "Name of the cluster.",
          "type": "string",
          "x-go-name": "Name"
        },
        "namespace": {
          "description": "Namespace of the cluster. Models the Kubernetes concept of Namespace as OpenShift Hive\nuses that to allow multiple clusters with the same name, separated by owner.",
          "type": "string",
          "x-go-name": "Namespace"
        }
      },
      "x-go-name": "Cluster",
      "x-go-package": "github.com/dgoodwin/syncsets/api"
    }
  },
  "responses": {
    "BadRequest": {
      "description": "BadRequest indicates that there was an error in\nthe HTTP request.",
      "headers": {
        "ResponseCode": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "OK": {
      "description": "OK indicates that the HTTP request was successful.",
      "headers": {
        "ResponseCode": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "createClusterBadRequest": {
      "description": "CreateClusterBadRequest BadRequest indicates that there was an error in\nthe HTTP request.",
      "headers": {
        "ResponseCode": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "createClusterOK": {
      "description": "CreateClusterOK OK indicates that the HTTP request was successful.",
      "headers": {
        "ResponseCode": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  }
}`))
}
