// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Standalone Hive SyncSets without reliance on Kube API, CRs, and etcd.",
    "title": "SyncSets API.",
    "contact": {
      "name": "Devan Goodwin",
      "email": "dgoodwin@redhat.com"
    },
    "license": {
      "name": "Apache2"
    },
    "version": "0.0.1"
  },
  "host": "localhost",
  "basePath": "/v1",
  "paths": {
    "/clusters": {
      "get": {
        "tags": [
          "clusters"
        ],
        "responses": {
          "200": {
            "description": "list the clusters",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/cluster"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/clusters/{name}": {
      "put": {
        "tags": [
          "clusters"
        ],
        "operationId": "update",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/cluster"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/cluster"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "clusters"
        ],
        "operationId": "delete",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "name",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "cluster": {
      "type": "object",
      "title": "Cluster is a representation of a Cluster we will reconcile SyncSets to.",
      "required": [
        "name",
        "namespace",
        "kubeconfig"
      ],
      "properties": {
        "kubeconfig": {
          "description": "Kubeconfig is an admin kubeconfig file for communicating with the cluster.",
          "type": "string",
          "x-go-name": "Kubeconfig"
        },
        "name": {
          "description": "Name of the cluster.",
          "type": "string",
          "x-go-name": "Name"
        },
        "namespace": {
          "description": "Namespace of the cluster. Models the Kubernetes concept of Namespace as OpenShift Hive\nuses that to allow multiple clusters with the same name, separated by owner.",
          "type": "string",
          "x-go-name": "Namespace"
        }
      },
      "x-go-name": "Cluster",
      "x-go-package": "github.com/dgoodwin/syncsets/api"
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Standalone Hive SyncSets without reliance on Kube API, CRs, and etcd.",
    "title": "SyncSets API.",
    "contact": {
      "name": "Devan Goodwin",
      "email": "dgoodwin@redhat.com"
    },
    "license": {
      "name": "Apache2"
    },
    "version": "0.0.1"
  },
  "host": "localhost",
  "basePath": "/v1",
  "paths": {
    "/clusters": {
      "get": {
        "tags": [
          "clusters"
        ],
        "responses": {
          "200": {
            "description": "list the clusters",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/cluster"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/clusters/{name}": {
      "put": {
        "tags": [
          "clusters"
        ],
        "operationId": "update",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/cluster"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/cluster"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "clusters"
        ],
        "operationId": "delete",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "name",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "cluster": {
      "type": "object",
      "title": "Cluster is a representation of a Cluster we will reconcile SyncSets to.",
      "required": [
        "name",
        "namespace",
        "kubeconfig"
      ],
      "properties": {
        "kubeconfig": {
          "description": "Kubeconfig is an admin kubeconfig file for communicating with the cluster.",
          "type": "string",
          "x-go-name": "Kubeconfig"
        },
        "name": {
          "description": "Name of the cluster.",
          "type": "string",
          "x-go-name": "Name"
        },
        "namespace": {
          "description": "Namespace of the cluster. Models the Kubernetes concept of Namespace as OpenShift Hive\nuses that to allow multiple clusters with the same name, separated by owner.",
          "type": "string",
          "x-go-name": "Namespace"
        }
      },
      "x-go-name": "Cluster",
      "x-go-package": "github.com/dgoodwin/syncsets/api"
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
